### ISSUE TITLE
More table tweaks

### ISSUE THREAD

**Issue by simonw** [simonw/laion-aesthetic-datasette#11]
Follow:
- #6

```css
.table-images .col-Link {
  display: none;
}
```

**Comment by simonw** [comment]
![image](https://user-images.githubusercontent.com/9599/187540749-59d281b1-3f4f-4743-bb5f-33e2a6308137.png)

**Comment by simonw** [comment]
```css
.table-images .col-rowid {
  display: none;
}
```
And use `?_nocol=` to hide `hash` and `__index_level_0__`.
